//
// Created by brill on 2016/9/8.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bril_jni_myJNI */

#ifndef _Included_com_bril_jni_myJNI
#define _Included_com_bril_jni_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bril_jni_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bril_jni_myJNI_sayHello
        (JNIEnv *env, jclass jobj){
    return (*env)->NewStringUTF(env,"vvvv lq");

}
#ifdef __cplusplus
}
#endif
#endif
